Bienvenu en Orgzly!

* Notes
** Cliquez sur la note pour l’ouvrir
** Cliquez et appuyez la note pour la sélectionner

Vous pouvez sélectionner plusieurs notes.

** Appuyez et déplacez rapidement vers droit pour ouvrir le menu rapide

** Appuyez et déplacez rapidement vers gauche pour ouvrir un menu diffèrent.

** Ouvrez une note qui contient des sub-notes en cliquant l'icône voisine
*** Il n’y a pas de limite au nombre de niveaux que vous pouvez avoir
**** Utilisez ceci pour mieux organiser vos notes

** Note peut avoir des étiquettes : tag1:tag2 :
*** La sub-note hérite les étiquettes :tag3:

Si vous recherchez des notes avec l'étiquette « tag1 », cette note sera retournée aussi de même.

** TODO La note peut avoir un état

Vous pouvez configurer n’importe quel nombre d’états à utiliser : TODO, NEXT, DONE, etc.

*** Il y a deux /types/ des États : choses à faire et fait

*** DONE C'est une note avec un type d'état /fait/
CLOSED: [2018-01-24 Mer 17:00]

** La note peut avoir un temps programmé
SCHEDULED: <2015-02-20 Ven 15:15>

*** L'horaire peut avoir un répetiteur
SCHEDULED: <2015-02-16 Lun .+1d>

** Vous pouvez également définir une écheance
DEADLINE: <2015-02-20 Fri>

** Les notes peuvent utiliser des liens

Composez un numéro de téléphone (tel:555-2368) ou [[sms:555-2368][send SMS]].

Envoyez un courriel [[mailto:support@orgzly.com][support@orgzly.com]], visitez http://www.orgzly.com ou lisez [[http://www.orgzly.com/help][documentation]].

** Un formatage base est supporté

Vous pouvez rendres les mots *en gras*, /italique/, _souligné_, =verbatim=, ~en code~ et +barré+.

* Cherchez
** Il y a beaucoup d’opérateurs de recherche supportés

Vous pouvez rechercher des notes par état, étiquette, pianification ou écheance et cetera.

Voir http://www.orgzly.com/help#search pour en savoir plus.

** Les requêtes de recherche peuvent être enregistrées pour un accès rapide

Essayez les recherches échantillon de menu et notez les requêtes qu’elles utilisent.

Vous pouvez créer vos propres recherches enregistrées en cliquant sur « Recherche » dans le menu de navigation.

* Synchronisation

** Les bloc-notes peuvent être énregistrées comme fichiers de texte

Les fichiers ont le format utilisé par "Org mode".

** Type de localisation (repository)

Vous pouvez maintenir les bloc-notes synchronisés avec un répertoire sur votre dispositif, carte de mémoire SD ou Dropbox.
