Bienvenue dans Orgzly!

* Notes
** Click on the note to select it

Vous pouvez sélectionner plusieurs notes.

** Ouvrez une note qui contient des sous-notes en cliquant sur l'icône voisine
*** Il n’y a pas de limite au nombre de niveaux que vous pouvez avoir
**** Vous pouvez utiliser ça pour mieux organiser vos notes

** Les notes peuvent avoir des étiquettes :tag1:tag2:
*** Les sous-notes héritent des étiquettes parentes :tag3:

Si vous recherchez des notes avec l'étiquette « tag1 », cette note sera également retournée.

** TODO Les notes peuvent avoir un état

Vous pouvez configurer tous les états que vous souhaitez : TODO, NEXT, DONE, etc.

*** Il y a deux /types/ d'état : à faire et terminé

*** DONE C'est une note avec un type d'état /fait/
CLOSED: [2018-01-24 Mer 17:00]

** La note peut avoir une date de début programmée
SCHEDULED: <2015-02-20 Ven 15:15>

*** L'horaire peut avoir un répetiteur
SCHEDULED: <2015-02-16 Mon .+2d>

** Vous pouvez également définir une échéance
DEADLINE: <2015-02-20 Fri>

** Les rappels pour les dates planifiées ou d'échéances sont supportés

Ils sont désactivés par défaut et doivent être activés dans les paramètres.

** [#A] Les notes peuvent avoir une priorité

Vous pouvez modifier le nombre de priorités dans les paramètres. Vous pouvez également changer la priorité par défaut - la priorité assumée lorsqu'elle n'est pas définie.

** Note can include links

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzly.com) or visit a webpage ([[http://www.orgzly.com][Orgzly.com]]).

You can also link to another note or notebook within the app.

See http://www.orgzly.com/help#links for more information.

** Un formatage de base est supporté

Vous pouvez mettre les mots en *gras*, /italique/, _souligné_, =verbatim=, ~en code~ ou les +biffer+.

** Liste de cases à cocher

- [X] Tâche 1
- [X] Tâche 2
- [X] Tâche 3

Un appui sur la case à cocher change son état. Un retour à la ligne crée une nouvelle case à cocher.

* Recherche
** Il y a beaucoup d’opérateurs de recherche supportés

Vous pouvez rechercher des notes par état, étiquette, planification, échéance, etc.

Voir http://www.orgzly.com/help#search pour en savoir plus.

** Les recherches peuvent être enregistrées pour un accès rapide

Essayez les exemples de recherche du menu et notez les requêtes qu’elles utilisent.

Vous pouvez créer vos propres recherches enregistrées en cliquant sur « Recherche » dans le menu de navigation.

* Synchronisation

** Les bloc-notes peuvent être enregistrés comme de simples fichiers de texte

Les fichiers suivent les règles de formatage « Org mode ».

** Emplacements des dépôts

Vous pouvez garder les bloc-notes synchronisés avec un dossier de votre appareil, sur une carte mémoire SD ou avec Dropbox.
