Willkommen bei Orgzly!

* Notizen
** Klicken Sie auf die Notiz, um sie zu öffnen
** Klicken und halten Sie die Notiz, um sie auszuwählen

** Sie können mehrere Notizen auswählen.

** Wischen Sie über der Notiz nach rechts, um das Schnell-Menü anzuzeigen

Nach Links wischen, um ein anderes Menü zu öffnen.

** Unterpunkte können Sie über das Symbole links und rechts daneben ein- und ausklappen
*** Es gibt keine Begrenzung in der Anzahl der Ebenen
**** Dies hilft dabei Ihre Notizen besser zu organisieren

** Notiz kann Tags enthalten :tag1:tag2:
*** tags werden an Unterpunkte vererbt :tag3:

Wenn Sie nach Notizen mit dem Tag "tag1" suchen, wird diese Notiz ebenfalls zurückgegeben.

** TODO Notizen können einen Status haben

Sie können eine beliebige Anzahl von Status konfigurieren: TODO, NEXT, DONE usw.

*** Es gibt zwei Arten von Status: to-do (zu erledigen), done (erledigt)

*** DONE Dies ist eine Notiz mit dem Status /done/ (also erledigt)
CLOSED: [2018-01-24 Wed 17:00]

** Sie können einen Termin festlegen
SCHEDULED: <2015-02-20 Fri 15:15>

*** Es gibt eine Wiederholungsfunktion für Termine
SCHEDULED: <2015-02-16 Mon .+1d>

** Sie können auch eine Frist festlegen
DEADLINE: <2015-02-20 Fri>

** Notiz unterstützt Verknüpfung (Hyperlinks)

Wählen Sie eine Telefonnummer (tel:555-2368) oder [[sms:555-2368][send SMS]].

Senden Sie eine E-Mail an [[mailto:support@orgzly.com][support@orgzly.com]], besuchen Sie http://www.orgzly.com oder lesen Sie [[http://www.orgzly.com/help][documentation]].

** Grundlegende typografische Hervorhebungen werden unterstützt

Sie können Wörter *fett*, /kursiv/, _unterstrichen_, =verbatim=, ~als Code~ und +durchgestrichen+ darstellen.

** Kontrollkästchenliste ist verfügbar

- [X] Aufgabe 1
- [ ] Aufgabe 2
- [ ] Aufgabe 3

Klicken Sie auf das Kontrollkästchen, um es zu wechseln. Drücken Sie neue Zeile am Ende der Zeile, um ein neues Element zu erstellen.

* Suchen
** Es werden viele Suchoperatoren unterstützt

Sie können Notizen nach Status (state), Auszeichner (tag), Termin (scheduled) oder Frist (deadline) usw. durchsuchen

Besuchen Sie http://www.orgzly.com/help#search um mehr darüber zu erfahren.

** Suchabfragen können für einen Schnellzugriff gespeichert werden

Probieren Sie die Beispielabfragen in der Navigationsleiste aus und schauen Sie sich an, wie diese Abfragen aufgebaut sind.

Sie können Ihre eigenen gespeicherten Suchen erstellen, indem Sie in der Navigationsleiste auf "Suchen" klicken.

Synchronisiere

** Notizbücher können als Nur-Text-Dateien gespeichert werden

Diese Dateien haben das "Org mode"-Format.

** Speicherort (Repository)

Sie können Notizbücher synchronisiert mit einem Verzeichnis auf Ihrem mobilen Gerät, SD-Karte oder Dropbox halten.
