Wilkommen bei Orgzly!

* Notizen
** Klicken Sie auf die Notiz, um sie zu öffnen
** Klicken und halten Sie die Notiz, um sie auszuwählen

Sie können mehrere Notizen auswählen.

** Notiz nach rechts wischen, um deren Schnellmenü zu öffnen

Notiz nach links wischen, um ein anderes Menü zu öffnen.

** Unterpunkte einer Notiz können Sie einklappen, indem Sie das Symbol neben ihr antippen

Halten Sie das Symbol gedrückt, um den gesamten Unterbaum aufzuklappen.

*** Es existiert keine Begrenzung bei der möglichen Anzahl der Ebenen
**** Dies hilft dabei, Ihre Notizen besser zu organisieren

** Notizen können Schlagwörter besitzen :Schlagwort1:Schlagwort2:
*** Unternotizen erben die Schlagwörter :tag3:

Wenn Sie mit der Abfrage „t.Schlagwort1“ nach Notizen mit dem Schlagwort „Schlagwort1“ suchen, wird diese Notiz in die Suchergebnisse aufgenommen.

*** Eine Notiz mit dem Schlagwort =ARCHIVE= ist ausgegraut :ARCHIVE:

** TODO-Notizen können einen Status besitzen

Sie können eine beliebige Anzahl zu verwendender Status konfigurieren: TODO, NEXT, DONE usw.

*** Es gibt zwei /Statusarten/: „to-do“ (zu erledigen) und „done“ (erledigt)

*** DONE Dies ist eine Notiz mit dem Status /done/ (also erledigt)
CLOSED: [2018-01-24 Wed 17:00]

** Sie können einen Termin festlegen
SCHEDULED: <2015-02-20 Fri 15:15>

*** Es gibt eine Wiederholungsfunktion für Termine
SCHEDULED: <2015-02-16 Mon .+2d>

** Sie können auch eine Frist festlegen
DEADLINE: <2015-02-20 Fri>

** Erinnerungen für Termine und Fristen

Erinnerungen für Termine und Fristen sind standardmäßig deaktiviert und können in den Einstellungen aktiviert werden.

** [#A] Notizen können priorisiert werden

Die verschiedenen Prioritätsstufen können in den Einstellungen verändert werden. Ebenso kann die Priorität angepasst werden, die Notizen ohne explizite Priorisierung zugeordnet wird.

** Notizen können Links enthalten

Wählen Sie eine Telefonnummer (tel:555-0199), senden Sie SMS (sms:555-0199), schreiben Sie eine E-Mail (mailto:support@orgzly.com) oder besuchen Sie eine Webseite ([[http://www.orgzly.com][Orgzly.com]]).

Sie können auch auf eine andere Notiz oder ein anderes Notizbuch innerhalb der App verweisen.

Siehe http://www.orgzly.com/help#links für weitere Informationen.

** Grundlegende typografische Hervorhebungen werden unterstützt

Sie können Wörter *fett*, /kursiv/, _unterstrichen_, =verbatim=, ~als Code~ und +durchgestrichen+ darstellen.

** Verwenden von Kontrollkästchen

- [X] Aufgabe 1
- [ ] Aufgabe 2
- [ ] Aufgabe 3

Klicken Sie auf das Kontrollkästchen, um es zu wechseln. Wenn Sie aus einer Zeile mit Kontrollkästchen eine neue Zeile erstellen, wird diese Zeile ebenfalls ein Kontrollkästchen beinhalten.

* Suchen
** Es werden viele Suchoperatoren unterstützt

Sie können Notizen nach Status (state), Schlagwort (tag), Termin (scheduled) oder Frist (deadline) usw. durchsuchen.

Besuchen Sie http://www.orgzly.com/help#search, um mehr zu erfahren.

** Suchabfragen können für den Schnellzugriff gespeichert werden

Probieren Sie die Beispielabfragen in der Navigationsleiste aus und schauen Sie sich an, wie diese Abfragen aufgebaut sind.

Sie können Ihre eigenen gespeicherten Suchen erstellen, indem Sie in der Navigationsleiste „Suchen“ antippen.

* Synchronisieren

** Notizbücher können als reine Textdateien gespeichert werden

Diese Dateien haben das "Org mode"-Format.

** Speicherort (Repository)

Notizbücher können in einem Verzeichnis auf Ihrem mobilen Gerät, der SD-Karte oder Ihrer Dropbox gespeichert und so synchronisiert werden.
