Wilkommen in Orgzly!

* Notizen
** Klicken Sie auf die Notiz, um sie zu öffnen
** Klicken und halten Sie die Notiz, um sie auszuwählen

Sie können mehrere Notizen auswählen.

** Wischen Sie über der Notiz nach rechts, um das Schnell-Menü anzuzeigen

Nach links wischen öffnet ein weiteres Menü.

** Unterpunkte können Sie über das Symbole links und rechts daneben ein- und ausklappen

Langer-Klick auf das Symbol, um das gesamte Unterverzeichnis zu entfalten.

*** Es gibt keine Begrenzung in der Anzahl der Ebenen
**** Dies hilft dabei Ihre Notizen besser zu organisieren

** Eine Notiz kann Tags enthalten :tag1:tag2:
*** Tags werden an Unterpunkte vererbt :tag3:

Wenn Ihre Suche nach Notizen mit Tag “Tag1”verwendet “t.tag1” Abfrage, diese Notiz wird in den Suchergebnissen mit eingeschlossen.

** TODO Notizen können einen Status haben

Sie können eine beliebige Anzahl von Status konfigurieren: TODO, NEXT, DONE usw.

*** Es gibt zwei Arten von Status: zu erledigen, erledigt

*** DONE Dies ist eine Notiz mit dem Status /done/ (also erledigt)
CLOSED: [2018-01-24 Wed 17:00]

** Sie können einen Termin festlegen
SCHEDULED: <2015-02-20 Fri 15:15>

*** Es gibt eine Wiederholungsfunktion für Termine
SCHEDULED: <2015-02-16 Mon .+2d>

** Sie können auch eine Frist festlegen
DEADLINE: <2015-02-20 Fri>

** Erinnerungen für Termine und Fristen

Erinnerungen für Termine und Fristen sind standardmäßig deaktiviert und können in den Einstellungen aktiviert werden.

** [#A] Notizen können priorisiert werden

Die verschiedenen Prioritätsstufen können in den Einstellungen verändert werden. Ebenso kann die Priorität angepasst werden, die Notizen ohne explizite Priorisierung zugeordnet wird.

** Notizen können Links enthalten

Wähle eine Telefonnummer (tel:555-0199), sende eine SMS (sms:555-0199), verfasse eine Email (mailto:support@orgzly.com), oder besuche eine Webseite ([[http://www.orgzly.com][Orgzly.com]]).

Sie können auch auf eine andere Notiz oder ein anderes Notizbuch innerhalb der App verweisen.

Siehe http://www.orgzly.com/help#links für weitere Informationen.

** Grundlegende typografische Hervorhebungen werden unterstützt

Sie können Wörter *fett*, /kursiv/, _unterstrichen_, =verbatim=, ~als Code~ und +durchgestrichen+ darstellen.

** Verwenden von Kontrollkästchen

- [X] Aufgabe 1
- [ ] Aufgabe 2
- [ ] Aufgabe 3

Klicken Sie auf das Kontrollkästchen, um es zu wechseln. Wenn Sie aus einer Zeile mit Kontrollkästchen eine neue Zeile erstellen, wird diese Zeile ebenfalls ein Kontrollkästchen beinhalten.

* Suchen
** Es werden viele Suchoperatoren unterstützt

Sie können Notizen nach Status (state), Tag (tag), Termin (scheduled) oder Frist (deadline) usw. durchsuchen

Besuchen Sie http://www.orgzly.com/help#search um mehr darüber zu erfahren.

** Suchabfragen können für den Schnellzugriff gespeichert werden

Probieren Sie die Beispielabfragen in der Navigationsleiste aus und schauen Sie sich an, wie diese Abfragen aufgebaut sind.

Sie können Ihre eigenen gespeicherten Suchen erstellen, indem Sie in der Navigationsleiste auf "Suchen" klicken.

* Synchronisiere

** Notizbücher können als Nur-Text-Dateien gespeichert werden

Diese Dateien haben das "Org mode"-Format.

** Speicherort (Repository)

Notizbücher können in einem Verzeichnis auf Ihrem mobilen Gerät, der SD-Karte oder Ihrer Dropbox gespeichert und so synchronisiert werden.
