Witaj w Orgzly!

* Notatki
** Kliknij notatkę, aby ją otworzyć
** Kliknij i przytrzymaj notatkę, aby ją zaznaczyć

Możesz zaznaczyć wiele notatek.

** Przeciągnij notatkę w prawo, aby otworzyć szybkie menu

Przeciągnij w lewo, aby otworzyć inne menu.

** Zwiń notatkę, która zawiera inne notatki, klikając ikonę „–” obok niej

Przytrzymaj ikonę „+”, aby rozwinąć wszystkie podrzędne notatki.

*** Liczba poziomów notatek jest nieograniczona
**** Wykorzystaj to, aby lepiej uporządkować swoje notatki

** Notatka może mieć przypisane znaczniki :znacznik1:znacznik2:
*** Podrzędna notatka dziedziczy znaczniki :znacznik3:

Jeśli wyszukasz notatki ze znacznikiem „znacznik1” za pomocą zapytania „t.znacznik1”, to ta notatka zostanie uwzględniona w wynikach wyszukiwania.

*** A note that has the =ARCHIVE= tag set is grayed out :ARCHIVE:

** TODO Notatka może mieć przypisany stan

Możesz skonfigurować dowolną liczbę stanów do użycia: TODO, NEXT, DONE, itp.

*** Istnieją dwa /typy/ stanów: do zrobienia i zrobione

*** DONE To jest notatka ze /zrobionym/ typem stanu
CLOSED: [2018-01-24 Wed 17:00]

** Notatka może mieć zaplanowany termin
SCHEDULED: <2015-02-20 Fri 15:15>

*** Zaplanowane terminy mogą się okresowo powtarzać
SCHEDULED: <2015-02-16 Mon .+2d>

** Możesz również ustawić termin ostateczny
DEADLINE: <2015-02-20 Fri>

** Obsługiwane są przypomnienia o zaplanowanych i ostatecznych terminach

Są one domyślnie wyłączone i muszą zostać włączone w ustawieniach.

** [#A] Notatka może mieć priorytet

Możesz zmienić liczbę poziomów priorytetów w ustawieniach. Możesz również zmienić domyślny priorytet, przypisywany notatkom, które nie mają ustawionego żadnego.

** Notatka może zawierać łącza

Wybierz numer telefonu (tel:123-456-789), wyślij wiadomość SMS (sms:123-456-789), napisz e-mail (mailto:support@orgzly.com) lub odwiedź stronę internetową ([[http://www.orgzly.com][Orgzly.com]]).

Możesz również zamieszczać łącza do innych notatek lub notatników w aplikacji.

Zobacz http://www.orgzly.com/help#links, aby uzyskać więcej informacji.

** Orgzly wspiera podstawowe formatowanie tekstu

Możesz stosować *pogrubienie*, /kursywę/, _podkreślenie_, =dosłowny tekst=, ~kod~ i +przekreślenie+.

** Możliwe jest tworzenie list do odhaczania

- [X] Zadanie „1”
- [ ] Zadanie „2”
- [ ] Zadanie „3”

Kliknij pole wyboru, aby je przełączyć. Naciśnij klawisz ENTER na końcu linii, aby utworzyć nowy element listy.

* Wyszukiwanie
** Istnieje wiele obsługiwanych operatorów wyszukiwania

Możesz wyszukiwać notatki według stanu, znaczników, zaplanowanego lub ostatecznego terminu itp.

Zobacz http://www.orgzly.com/help#search, aby dowiedzieć się więcej.

** Aby uzyskać szybki dostęp do wyszukań, można je zapisać

Wypróbuj przykładowe wyszukiwania z szuflady nawigacyjnej i zwróć uwagę na użyte w nich zapytania.

Możesz utworzyć własne wyszukiwania, klikając na „Wyszukiwania” w szufladzie nawigacyjnej.

* Synchronizacja

** Notatniki mogą być zapisywane jako zwykłe pliki tekstowe

Pliki zapisywane są w formacie używanym przez „Org-mode”.

** Typ lokalizacji (repozytorium)

Możesz synchronizować notatniki z katalogiem na swoim urządzeniu mobilnym, karcie SD lub Dropboxie.
