#+BEGIN_HTML
<a title="Build" target="_blank" href="https://github.com/orgzly-community/orgzly-android/actions/workflows/android-build-master.yml"><img src="https://github.com/orgzly-community/orgzly-android/actions/workflows/android-build-master.yml/badge.svg"></a>
<a title="Crowdin" target="_blank" href="https://crowdin.com/project/orgzly"><img src="https://d322cqt584bo4o.cloudfront.net/orgzly/localized.svg"></a>
#+END_HTML

* Orgzly Revived

Orgzly is an outliner for taking notes and managing to-do lists.

You can keep notebooks stored in plain-text and have them synchronized
with a directory on your mobile device, SD card, WebDAV server or Dropbox.

Notebooks are saved in /Org mode/'s file format. “Org mode is for
keeping notes, maintaining TODO lists, planning projects, and
authoring documents with a fast and effective plain-text system.” See
http://orgmode.org for more information.

Orgzly Revived is a community fork of Orgzly, launched because of an absence of
communication from the creator of the original app.

** End-user documentation

Find out more here: https://github.com/orgzly/documentation

** Building & testing

If you don't use Android Studio and wish to [[https://developer.android.com/studio/build/building-cmdline.html][build]] and [[https://developer.android.com/studio/test/command-line.html][test]] the app
from command line, the standard set of Gradle tasks is available.  For
example:

- ~./gradlew build~ builds the project and generates APK files
- ~./gradlew connectedAndroidTest~ runs instrumented unit tests

Make sure you [[https://developer.android.com/training/testing/espresso/setup][turn off animations]] for the device you're testing on.

** License

The project is licensed under the [[https://github.com/orgzly-community/orgzly-android/blob/master/LICENSE][GNU General Public License version 3 (or newer)]].
