Ласкаво просимо до Orgzly!

* Нотатки
Натисніть, щоб відкрити нотатку
Щоб вибрати нотатку натисніть і утримуйте її

Можна виділити кілька нотаток.

Потяніть нотатку вправо щоб відкрити швидке меню

Потяніть нотатку вліво, щоб відкрити додаткове меню.

** Щоб згорнути нотатку з вкладеним вмістом, натисніть на значок поряд з нею

Довге натискання на іконці розгортає весь вміст.

*** Нотатки можуть мати скільки завгодно рівней вкладення
**** Скористайтесь цим, щоб краще организувати ваші нотатки

** До нотаток можна додавати теги :тег1:тег2:
*** Вкладені нотатки наслідують теги :тег3:

Якщо ви шукаєте нотатки з тегом "tag1" використовуючи запит "t.tag1", то ця примітка буде включена до результатів пошуку.

*** Нотатка з тегом =ARCHIVE= виділяється сірим :ARCHIVE:

** TODO Нотатки можуть мати стан

Ви можете налаштувати любу кількість станів та використовувати їх: TODO, NEXT, DONE і т. д.

*** Є два /типу/ станів: заплановані(to-do) та виконані(done)

*** DONE Це нотатка з /виконаним/ типом стану
CLOSED: [2018-01-24 Wed 17:00]

** Нотатки дозволяють запланувати час
SCHEDULED: <2015-02-20 Fri 15:15>

*** Час може повторюватися
SCHEDULED: <2015-02-16 Mon .+2d>

** Ви також можете встановити час завершення
DEADLINE: <2015-02-20 Fri>

** Підтримуються нагадування для нотаток з запланованим часом або завершенням

За замовчанням вони вимкнені і їх необхідно увімкнути в Налаштуваннях.

** [#A] Нотатки можуть мати приорітет

Ви можете змінити кількість приорітетів в Налаштуваннях. Також ви можете змінити стандартний приорітет, який пропонується для нотаток, де його не було встановлено.

** Нотатка може мати посилання

Подзвоніть за номером (tel:555-0199), відправте SMS (sms:555-0199), пошту (mailto:support@orgzly.com) или відвідайте веб-сторінку ([[http://www.orgzly.com][Orgzly.com]]).

Також ви можете послатися на іншу нотатку або блокнот.

Відвідайте http://www.orgzly.com/help#links щоб взнати більше.

** Підтримуються базові типографічні засоби виразності

Ви можете зробити текст *жирним*, /курсивним/, _підкресленим_, =виділеним=, ~моношириним~ та +закресленим+.

** Є список з вимикачами

- [X] Задача 1
- [ ] Задача 2
- [ ] Задача 3

Натисніть на вимикач, щоб змінити стан. Натисніть кнопку нового рядка *⤶* на кінці рядка, щоб додати новий елемент.

* Пошук
** Підтримуються різноманітні критерії пошуку

Ви можете шукати нотатки за станом, тегам, встановленому або часом завершення і т. і.

Відвідайте http://www.orgzly.com/help#search щоб взнати більше.

** Пошукові запити можна зберігати для повторного використання

Спробуйте приклади збережених пошуків в меню навігації та ознакомьтесь с запитами, які вони використовують.

Ви можете створити ваші власні пошукові запити натиснувши на "Пошукові запити" в меню навігації.

* Синхронізація

** Блокноти можна зберігати як прості текстові файли

Файли знаходяться в форматі, що використорує  ([[https://orgmode.org/][org-mode]]).

** Тип розміщєння (сховище)

Ви можете зберігати ваші блокноти в папці на вашому мобільному пристрої, SD-карті чи в Dropbox.
