Добро пожаловать в Orgzly!

* Заметки
** Нажатие для открытия заметки
** Долгое нажатие для выбора заметки

Можно выбрать несколько заметок.

** Смахивание вправо для вызова быстрого меню

Смахивание влево для вызова дополнительного меню.

** Чтобы свернуть заметку с вложенным содержимым, нажмите на значок рядом с ней

Долгое нажатие на значок разворачивает всё поддерево.

*** У заметок может быть сколько угодно уровней вложенности
**** Используйте эту возможность, чтобы лучше организовать свои заметки

** Заметкам можно добавить теги :тег1:тег2:
*** Вложенные заметки наследуют теги :тег3:

При поиске заметки с тегом «tag1» с помощью запроса «t.tag1», эта заметка будет включена в результаты поиска.

*** Заметка с тегом =ARCHIVE= выделяется серым цветом :ARCHIVE:

** TODO Заметки могут иметь состояние

Вы можете настроить любое количество состояний и использовать их: TODO, NEXT, DONE и т. д.

*** Существует два /типа/ состояний: запланированные (todo) и выполненные (done)

*** DONE Это заметка с /выполненным/ типом состояния
CLOSED: [2018-01-24 Wed 17:00]

** Заметки могут иметь назначенное время
SCHEDULED: <2015-02-20 Fri 15:15>

*** Время заметки может быть повторяемым
SCHEDULED: <2015-02-16 Mon .+2d>

** Вы также можете установить крайний срок для заметки
DEADLINE: <2015-02-20 Fri>

** Поддерживаются напоминания для заметок с назначенным временем или крайним сроком

По умолчанию они отключены и их необходимо включить в «Настройках».

** [#A] Заметки могут иметь приоритет

Вы можете изменить количество приоритетов в «Настройках». Вы также можете изменить приоритет по умолчанию - подразумеваемый приоритет для заметок без установленного приоритета.

** Заметка может содержать ссылки

Позвонить по телефону (tel:555-0199), отправить SMS (sms:555-0199), отправить электронную почту (mailto:support@orgzly.com) или посетить веб-страницу ([[http://www.orgzly.com][Orgzly.com]]).

Вы так же можете сослаться на другую заметку или блокнот.

Для дополнительной информации смотрите http://www.orgzly.com/help#links

** Поддерживаются базовые средства выразительности типографики

Вы можете сделать текст *жирным*, /курсивным/, _подчёркнутым_, =выделенным=, ~моноширинным~ и +зачёркнутым+.

** Доступен список с флажками

- [X] Задача 1
- [ ] Задача 2
- [ ] Задача 3

Нажмите флажок, чтобы изменить его. Нажмите кнопку новой строки в конце линии, чтобы создать новый элемент.

* Поиск
** Поддерживаются разнообразные критерии поиска

Вы можете искать заметки по состоянию, тегам, назначенному или крайнему сроку и т. д.

Посетите http://www.orgzly.com/help#search , чтобы узнать больше.

** Поисковые запросы можно сохранять для повторного использования

Попробуйте примеры сохранённых поисков в меню навигации и ознакомьтесь с используемыми в них запросами.

Вы можете сохранять ваши собственные поисковые запросы нажатием на «Поисковые запросы» в меню навигации.

* Синхронизация

** Блокноты можно сохранять в виде простых текстовых файлов

Файлы находятся в формате, используемом в «Режим Org».

** Тип расположения (хранилища)

Вы можете хранить ваши блокноты в папке на вашем мобильном устройстве, SD-карте или в Dropbox.
