Добро пожаловать в Orgzly!

* Заметки
** Нажмите на заметку, чтобы открыть
** Нажмите и удерживайте заметку, чтобы выбрать

Можно выбрать несколько заметок.

** Смахните заметку вправо, чтобы открыть быстрое меню

Смахните влево, чтобы открыть дополнительное меню.

** Чтобы свернуть заметку с вложенным содержимым, нажмите на значок рядом с ней
*** У заметок может быть сколько угодно уровней вложенности
**** Используйте эту возможность, чтобы ваши заметки были лучше организованы

** Заметкам можно добавить теги :тег1:тег2:
*** Вложенные заметки наследуют теги :тег3:

При поиске заметок с тегом "тег1" эта заметка тоже найдётся.

** TODO Заметки могут иметь состояние

Вы можете настроить любое количество состояний и использовать их: TODO, NEXT, DONE и т. д.

*** Существует два /типа/ состояний: запланированные(to-do) и выполненные(done)

*** DONE Это заметка с /выполненным/ типом состояния
CLOSED: [2018-01-24 Wed 17:00]

** Заметки могут иметь назначенное время
SCHEDULED: <2015-02-20 Fri 15:15>

*** Время заметки может быть повторяемым
SCHEDULED: <2015-02-16 Mon .+1d>

** Вы также можете установить крайний срок для заметки
DEADLINE: <2015-02-20 Fri>

** В заметках можно использовать ссылки

Позвоните по номеру телефона (tel:555-2368) или [[sms:555-2368][отправьте SMS]].

Отправьте сообщение на почту [[mailto:support@orgzly.com][support@orgzly.com]], посетите http://www.orgzly.com или прочтите [[http://www.orgzly.com/help][документацию]].

** Поддерживаются базовые средства выразительности типографики

Вы можете сделать текст *жирным*, /курсивным/, _подчеркнутым_, =выделенным=, ~моноширинным~ и +зачеркнутым+.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press new-line button at the end of the line to create a new item.

* Поиск
** Поддерживаются разнообразные критерии поиска

Вы можете искать заметки по состоянию, тегам, назначенному или крайнему сроку и т. д.

Посетите http://www.orgzly.com/help#search чтобы узнать больше.

** Поисковые запросы можно сохранять для повторного использования

Попробуйте примеры сохраненных поисков в меню навигации и ознакомьтесь с используемыми в них запросами.

Вы можете сохранять ваши собственные поисковые запросы нажатием на "Поисковые запросы" в меню навигации.

* Синхронизация

** Блокноты можно сохранять в виде простых текстовых файлов

Файлы находятся в формате, используемом в “Режим Org”.

** Тип расположения (хранилища)

Вы можете хранить ваши блокноты в папке на вашем мобильном устройстве, SD-карте или в Dropbox.
