歡迎使用 Orgzly!

* 筆記
** 點擊筆記打開
** 長按住筆記以選中它

您可以選擇多個筆記。

** 滑動筆記打開快速功能表

左滑動, 打開不同的功能表。

** 通過按一下旁邊的圖示來折疊包含子項目的筆記
您可以擁有無限的筆記階層數
用這個來更好的整理你的筆記

** 筆記可以有標籤如： :標籤1:標籤2:
子項目會繼承母項目的標記：:標籤3:

如果您搜索帶有標記 "標籤1" 的筆記, 則也會搜尋到該子項目筆記。

** TODO 筆記可以有一個狀態

您可以配置任意數量的狀態來使用: TODO、NEXT、DONE，等。

有兩種狀態類型: "待辦"與"完成"

*** DONE 是筆記“完成”類型的狀態
CLOSED: [2018-01-24 Wed 17:00]

** 筆記可以有預定日程"scheduled"的時間
SCHEDULED: <2015-02-20 Fri 15:15>

*** 時間可以重複
SCHEDULED: <2018-02-16 Tue .+1d>

** 還可以設置截止時間
DEADLINE: <2018-02-20 Sat>

** 筆記可以使用連結

撥通一個電話號碼使用 (tel:555-2368) 或是 [[sms:555-2368][send SMS]]

寄郵件 [[mailto:support@orgzly.com][support@orgzly.com]], 請參考 http://www.orgzly.com 或讀取 [[http://www.orgzly.com/help][documentation]]

** 筆記支持基本的標記重點

你可以用兩個符號包圍字串改變文字形態如：*粗體*, /斜體/, _底線_, =代碼=, ~逐字的~, +刪除線+。

** 核取方塊清單可用

- [X] 任務1
-[ ] 任務2
-[ ] 任務3

按一下核取方塊以切換它。 按下行末的new-line新建行，創建新項目

* 搜尋
** 有許多支援的搜索操作符

您可以按狀態、標籤、日程“schedule"或截止時間"deadline"等來搜索筆記。

請參閱 http://www.orgzly.com/help#search 瞭解更多。

** 可以將搜尋保存以便快速訪問

嘗試使用導航抽屜中的搜尋範本, 並記下他們使用的查詢語法。

您可以通過按一下導航抽屜中的 "搜尋" 來創建自己保存的搜尋。

* 同步

** 筆記本可保存為純文字檔

檔案採用 "org-mode" 所使用的格式。

** 位置 (存儲庫) 類型

您可以將筆記本與行動裝置上的目錄、SD 卡或Dropbox保持同步。
