歡迎使用 Orgzly!

* 筆記
** 點選以打開筆記
** 點選並長按住筆記以選中它

您可以選擇多個筆記。

** 向右滑動筆記打開快速功能表

向左滑動以打開其他功能表

** 通過按一下旁邊的圖示來折疊包含子項目的筆記

長按圖示展開子樹集

您可以擁有無限的筆記階層數
用這個來更好的整理你的筆記

** 筆記可以有標籤如： :標籤1:標籤2:
子項目會繼承母項目的標記：:標籤3:

如果使用“t.tag1”收尋，若筆記有“tag1”的標籤，則此筆記將包含在收尋結果中。

*** 將設有= ARCHIVE = 歸檔標籤的筆記變灰 :ARCHIVE:

** TODO 筆記可以有一個狀態

您可以配置任意數量的狀態來使用: TODO、NEXT、DONE，等。

有兩種狀態類型: "待辦"與"完成"

*** DONE 是筆記“完成”類型的狀態
CLOSED: [2018-01-24 Wed 17:00]

** 筆記可以有預定日程"scheduled"的時間
SCHEDULED: <2015-02-20 Fri 15:15>

*** 時間可以重複
SCHEDULED: <2015-02-16 Mon .+2d>

** 還可以設置截止時間
DEADLINE: <2018-02-20 Sat>

** 支援行事曆和截止時間的提醒

預設情況下, 它們處於禁用狀態, 需要在設置中啟用。

** [#A] 注釋可以具有優先順序

您可以在 "設置" 中更改優先順序的數量。 您還可以更改預設優先順序，假使沒有筆記的優先順序。

** 筆記可以包含連結

撥打電話號碼 (tel:555-0199), 傳送簡訊 (sms:555-0199), 撰寫電子郵件 (mailto:support@orgzly.com) 或訪問網頁 ([[http://www.orgzly.com][Orgzly.com]])。

你還可以連結到其他筆記或筆記本。

有關詳細資訊, 請參閱 http://www.orgzly.com/help#links。

** 筆記支持基本的標記重點

你可以用兩個符號包圍字串改變文字形態如：*粗體*, /斜體/, _底線_, =代碼=, ~逐字的~, +刪除線+。

** 核取方塊清單可用

- [X] 任務1
-[ ] 任務2
-[ ] 任務3

按一下核取方塊以切換它。 按下行末的new-line新建行，創建新項目

* 搜尋
** 有許多支援的搜索操作符

您可以按狀態、標籤、日程“schedule"或截止時間"deadline"等來搜索筆記。

請參閱 http://www.orgzly.com/help#search 瞭解更多。

** 可以將搜尋保存以便快速訪問

嘗試使用導航抽屜中的搜尋範本, 並記下他們使用的查詢語法。

您可以通過按一下導航抽屜中的 "搜尋" 來創建自己保存的搜尋。

* 同步

** 筆記本可保存為純文字檔

檔案採用 "org-mode" 所使用的格式。

** 位置 (存儲庫) 類型

您可以將筆記本與行動裝置上的目錄、SD 卡或Dropbox保持同步。
