欢迎使用Orgzly！

* 笔记
** 点击打开笔记
** 点击并长按选择笔记

可选择多条笔记。

** 右划笔记打开快捷菜单

左划笔记打开另一个菜单。

** 点击笔记旁的图标收起笔记的子笔记
*** 层级数量没有限制
**** 以此来更好地组织笔记

** 笔记可带有标签 :tag1:tag2:
*** 子笔记继承标签 :tag3:

在搜索带有标签“tag1”的笔记时，此笔记也将被作为结果返回。

** 待办 笔记可具有一种状态

可配置任意数量的状态使用：待办，接下来，完成等。

*** 有两种/类型/的状态：待办和完成

*** 完成 这是一条具有/完成/类型状态的笔记
CLOSED: [2018-01-24 Wed 17:00]

** 笔记可以有一个计划时间
SCHEDULED: <2015-02-20 Fri 15:15>

*** 时间可以设定一个重复器
SCHEDULED: <2015-02-16 Mon .+2d>

** 也可以设定一个截止时间
DEADLINE: <2015-02-20 Fri>

** 支持计划时间和截至时间的提醒

默认为关闭，需要在设置中启用。

** [#A] 笔记可以具有优先级

可在设置中更改优先级数量 也可以更改默认优先级 - 假如笔记的优先级没有设定。

** 笔记可以包含链接

拨打电话 (tel:555-0199)，发送短信 (sms:555-0199)，写邮件 (mailto:support@orgzly.com) 或访问网页 ([[http://www.orgzly.com][Orgzly.com]])。

也可以在应用序内链接到其他笔记或笔记本。

访问 http://www.orgzly.com/help#links 了解更多信息。

** 支持基本的排版强调

您可以使文字 *粗体* ， /斜体/ ， _下划线_ ， =逐字= ， ~代码~ 和 +删除线+ 。

** 支持复选框列表

- [X] 任务 1
- [ ] 任务 2
- [ ] 任务 3

点击复选框切换。 点按行尾的新建行按钮以创建新条目。

* 搜索
** 支持多种搜索运算符

可通过状态，标签，计划时间或截止时间等搜索笔记

访问 http://www.orgzly.com/help#search 了解更多。

** 可保存搜索查询串以便快速访问

从导航抽屉中尝试示例搜索并注意它们所使用的查询串。

可通过点击导航抽屉中的“搜索”创建和保存自定义搜索。

* 同步

** 笔记本可保存为纯文本文件

文件使用“Org mode”的格式。

** 位置(存储库)类型

可使笔记本与移动设备，SD卡或Dropbox上的一个目录保持同步。
