欢迎来到Orgzly!

* 笔记
** 点击笔记来打开它
** 点击并按住笔记来选择它

您可以选择多条笔记。

** 右划笔记以打开快速菜单

左划笔记打开一个不同的菜单。

** 通过点击旁边的图标来折叠一条包含子笔记的笔记
*** 您可以拥有无限数量的层级
**** 利用这一点来更好地组织笔记
** 笔记可以有标签 :标签1:标签2:
*** 子笔记继承标签 :标签3:

如果您搜索标记有“标签1”的笔记，这条笔记也将作为结果被返回。

** [#A] 笔记可以有优先级
** 待办任务是一种具有待办状态的笔记类型

您可以拥有任何数量的不同状态（待办，等待，...）。您可以在“设置”中配置状态。

** 待办 您可以设定计划时间
SCHEDULED: <2015-02-20 Fri 15:15>

** 待办 您可以设定截止时间
DEADLINE: <2015-02-20 Fri> SCHEDULED: <2015-02-23 Mon>

可以同时使用计划时间和截止时间。

** 已完成任务可以通过将其状态设置为已完成来标记为完成
CLOSED: [2015-02-20 Fri 20:17]

** 笔记可以包含不同类型的链接

拨打电话 (tel:555-2368) 或 [[sms:555-2368][发送短信]].

发送邮件到 [[mailto:support@orgzly.com][support@orgzly.com]], 访问 http://www.orgzly.com 或阅读 [[http://www.orgzly.com/help][documentation]].

开始编辑此内容以检查语法。

* 搜索
** 您可以通过点击搜索图标来搜索笔记
** 您可以搜索出现在笔记中任何地方的文本，或使用搜索运算符缩小搜索结果范围

访问 http://www.orgzly.com/help#Search 获取更多信息。

** 搜索查询可以保存为快速访问

有两个默认保存的搜索在导航抽屉可用。尝试它们并注意使用的运算符。

*** 您可以在导航抽屉中通过点击“搜索”来定义您自己的搜索
* 设置

设置按钮位于导航抽屉中。

** 查看可用的设置

根据您的喜好修改它们来提升使用Orgzly的体验。试试黑色主题！


* 同步
** 同步方式

笔记本可以和您设备上的目录或Dropbox同步。很快，将支持额外的存储类型，比如Git，Google Drive，SSH以及更多。

** 您的笔记本被保存为纯文本文件

文件是使用“Org mode”的格式。

** 从设置中添加一个存储库

存储库只是一个在您的设备上或Dropbox中的目录。

** 开始同步

同步目前是手动的。按钮位于导航抽屉中。

