欢迎使用Orgzly！

* 笔记
** 点击笔记来打开它
** 点击并长按笔记来选择它

您可以选择多条笔记。

** 右划笔记以打开它的快捷菜单

左划笔记来打开一个不同的菜单。

** 点击笔记旁的图标可收起包含子笔记的笔记
*** 层级的数量没有限制
**** 以此来更好地组织您的笔记

** 笔记可以具有标签：标签1：标签2：
*** 子笔记继承标签：标签3：

如果您搜索具有标签“标签1”的笔记，这条笔记也将被作为结果返回。

** 待办 笔记可以具有一种状态

您可以配置任意数量的状态来使用：待办，接下来，完成，等。

*** 有两种/类型/的状态：待办和完成

*** 完成 这是一条具有/完成/类型状态的笔记
CLOSED: [2018-01-24 Wed 17:00]

** 笔记可以有一个计划时间
SCHEDULED: <2015-02-20 Fri 15:15>

*** 时间可以设定一个重复器
SCHEDULED: <2015-02-16 Mon .+1d>

** 您也可以设定一个截止时间
DEADLINE: <2015-02-20 Fri>

** 笔记可以使用链接

拨打电话号码(tel:555-2368) 或 [[sms:555-2368][发送短信]]。

发送邮件到 [[mailto:support@orgzly.com][support@orgzly.com]]，访问 http://www.orgzly.com 或阅读[[http://www.orgzly.com/help][documentation]]。

** 支持基本的排版强调

您可以使文字 *粗体* ， /斜体/ ， _下划线_ ， =逐字= ， ~代码~ 和 +删除线+ 。

** 复选框列表可用

- [X] 任务 1
- [ ] 任务 2
- [ ] 任务 3

点击复选框以切换。 轻按行尾的新建行按钮以创建新条目。

* 搜索
** 支持大量搜索运算符

您可以通过状态，标签，计划时间或截止时间等搜索笔记。

查看 http://www.orgzly.com/help#search 了解更多。

** 搜索查询串可以被保存以便快速访问

从导航抽屉中尝试示例搜索并注意它们所使用的查询串。

您可以通过点击导航抽屉中的“搜索”来创建并保存自己的搜索。

* 同步

** 笔记本可以被保存为纯文本文件

文件使用“Org mode”的格式。

** 位置(存储库)类型

您可以使笔记本与您的移动设备，SD卡或Dropbox上的一个目录保持同步。
