Orgzly에 오신 것을 환영합니다!

* 메모
** 메모 내용을 보시려면 클릭하세요.
** 메모를 선택하시려면 길게 클릭하세요.

여러개의 메모를 선택할 수 있습니다.

** 메모의 오른쪽을 선택하면 퀵메뉴를 열 수 있습니다.

왼쪽을 선택하면 다른 메뉴가 열립니다.

** 옆의 아이콘을 눌러서 하위 메모를 숨길 수 있습니다.

Long-click the icon to unfold entire subtree.

*** 제한없이 하위 메모를 만들 수 있습니다.
**** 메모를 잘 정리하려면 이 항목을 사용하세요.

** 메모에 태그를 달 수 있습니다 :tag1:tag2:
*** 하위 메모는 상위 메모의 태그를 물려받습니다. :tag3:

If you search for notes with tag “tag1” using “t.tag1” query, this note will be included in search results.

*** A note that has the =ARCHIVE= tag set is grayed out :ARCHIVE:

** TODO 메모에 처리 상태를 설정할 수 있습니다.

처리상태: TODO, NEXT, DONE, etc.

*** 두 /종류/의 상태 : 할 일과 완료

*** DONE 메모의 처리가 /완료/되었습니다.
CLOSED: [2018-01-24 Wed 17:00]

** 예정일을 설정할 수 있습니다.
SCHEDULED: <2015-02-20 Fri 15:15>

*** 일정을 반복할 수 있습니다.
SCHEDULED: <2015-02-16 Mon .+2d>

** 마감일을 설정할 수 있습니다.
DEADLINE: <2015-02-20 Fri>

** 예정일과 마감일에 대해 알림 기능을 제공합니다.

기본적으로 알림이 해제되어 있으므로, 설정에서 변경하시기 바랍니다.

** [#A] 메모에 우선 순위를 설정할 수 있습니다.

우선 순위를 변경할 수 있습니다. 우선 순위를 설정하지 않은 메모에 대한 기본 우선 순위를 변경할 수 있습니다.

** 노트에 바로 가기를 사용할 수 있습니다.

전화 걸기 (tel:555-0199), 문자 보내기 (sms:555-0199), 이메일 발송 (mailto:support@orgzly.com), 인터넷 연결 ([[http://www.orgzly.com][Orgzly.com]]).

앱 내의 다른 메모나 메모장도 바로 가기를 사용할 수 있습니다.

자세한 내용은 "http://www.orgzly.com/help#links" 참고하세요.

** 기본적인 글자 강조 기능을 사용할 수 있습니다.

*굵게*, /기울기/, _밑줄_, =인용=, ~수식~, +취소+ 단어를 표현할 수 있습니다.

** 확인란 목록을 사용할 수 있습니다.

- [X] 작업 1
- [ ] 작업 2
- [ ] 작업 3

확인 란을 클릭하면 상태가 변경됩니다. 줄 끝에 있는 새 줄 단추를 눌러 새 항목을 만드세요.

* 찾기
** 다양한 방법으로 메모를 검색할 수 있습니다.

메모의 상태, 예정일, 종료일 등 으로도 검색할 수 있습니다.

자세한 내용은 "http://www.orgzly.com/help#search" 참고하세요.

*** 자주사용하는 검색 방법을 저장할 수 있습니다.

네비게이션 메뉴에서 기본 제공된 검색 방법을 이용해보시기 바랍니다.

네비게이션 메뉴에서 "찾기"를 클릭하시면 기본 제공된 검색 방법을 수정할 수 있습니다.

* 동기화

** 메모장은 텍스트 파일로 저장됩니다.

텍스트 파일의 확장자는 org 입니다.

** 저장소 종류

핸드폰 저장소나 드랍박스에 동기화 기능으로 메모장을 저장할 수 있습니다.
