Welcome to Orgzly!

* Notes
** Click on the note to open it
** Click and hold the note to select it

You can select multiple notes.

** Fling note right to open its quick-menu

Fling it left to open a different menu.

** Fold a note which contains sub-notes by clicking the icon next to it

Long-click the icon to unfold entire subtree.

*** There is no limit in number of levels you can have
**** Use this to better organize your notes
** Note can have tags :tag1:tag2:
*** Sub-note inherits the tags :tag3:

If you search for notes with tag “tag1” using “t.tag1” query, this note will be included in search results.

*** A note that has the =ARCHIVE= tag set is grayed out :ARCHIVE:
** TODO Note can have a state

You can configure any number of to-do states (e.g. TODO, NEXT, …) and done states (e.g. DONE, CNCL, …)

*** DONE This is a note with done type of state
CLOSED: [2018-01-24 Wed 17:00]

** Note can have a scheduled time
SCHEDULED: <2015-02-20 Fri 15:15>

*** Times can have a repeater
SCHEDULED: <2015-02-16 Mon .+2d>

** You can also set a deadline time
DEADLINE: <2015-02-20 Fri>

** Reminders are triggered for scheduled and deadline times

Mark the note as done to shift the repeater.

** [#A] Note can have a priority

You can change the number of priorities in Settings. You can also change default priority - assumed priority for notes without one set.

** Note can include links

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzly.com) or visit a webpage ([[http://www.orgzly.com][Orgzly.com]]).

You can also link to another note or notebook within the app.

See http://www.orgzly.com/help#links for more information.

** Basic typographical emphasis is supported

You can make words *bold*, /italic/, _underlined_, =verbatim=, ~code~ and +strike-through+.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press new-line button at the end of the line to create a new item.

* Search
** There are many search operators supported

You can search notes by state, tag, scheduled or deadline time etc.

See http://www.orgzly.com/help#search to learn more.

** Saved searches are supported

Try sample searches from the navigation drawer and note the queries they use.

You can create your own saved searches by clicking on “Searches” in the navigation drawer.

* Syncing
** Repository

Repository is a location you can sync your notebooks with. Repository can be a directory on your mobile device, SD card or Dropbox.

** Notebooks are saved as plain-text files

Files are in the format used by [[https://orgmode.org/][Org mode]].

