Üdv az Orgzly jegyzetelőben!

* Jegyzetek
** Koppints a bejegyzés megnyitásához
** Tartsd lenyomva a bejegyzés kijelöléséhez

Kijelölhetsz több bejegyzést is.

** Jobbra simítva megnyílik a gyorsmenü

Balra simítva egy másik menü nyílik meg.

** Ha egy bejegyzés tartalmaz aljegyzeteket is, be lehet hajtogatni azokat, ha az ikonra koppintasz mellette

Hosszú koppintás az ikonon megnyitja az egész fát.

*** Nincs korlátozva, hogy hány szinten lehet aljegyzet
**** Így könnyebb elrendezni a bejegyzéseket

** Lehet címkéket is ragasztani bejegyzésekre :címke1:címke2:
*** Az aljegyzet örökli a címkéket :címke3:

Ha a "címke1" címkéjű bejegyzéseket keresed a "t.címke1" lekérdezés használatával, akkor ez a bejegyzés benne lesz a keresési eredményben.

*** Az =ARCHIVE= -nak cimkézett jegyzet kiszürkített :ARCHIVE:

** TODO Egy bejegyzésnek állapota is lehet

Létre lehet hozni akárhány állapot jelzőt: TODO, NEXT, DONE, stb.

*** Kétféle /típusa/ lehet az állapotoknak: to-do (tennivaló) és done (kész)

*** DONE Ennek a bejegyzésnek az állapota /done/, vagyis /kész/
CLOSED: [2018-01-24 Wed 17:00]

** Egy bejegyzést ütemezni is lehet
SCHEDULED: <2015-02-20 Fri 15:15>

*** Ismétlődő időt is be lehet állítani
SCHEDULED: <2015-02-16 Mon .+2d>

** Határidőt is be lehet állítani
DEADLINE: <2015-02-20 Fri>

** Az ütemezett és a határidőkhöz emlékeztetőt is lehet beállítani

Alaphelyzetben ez le van tiltva, engedélyezni kell a Beállításokban.

** [#A] Egy jegyzetnek lehet prioritása

A prioritások számát megadhatod a Beállításokban. Az alap prioritást is át lehet állítani - bármely bejegyzésnek ez lesz a prioritása ha nincs külön beállítva.

** Linket is tartalmazhat egy bejegyzés

Hívj fel egy számot (tel:555-0199), küldj SMS-t (sms:555-0199), írj emailt (mailto:support@orgzly.com) vagy látogass meg egy weboldalt ([[http://www.orgzly.com][Orgzly.com]]).

Lehet más bejegyzéshez vagy az appon belül másik jegyzetfüzethez is linket megadni.

További információ a http://www.orgzly.com/help#links címen.

** Az alapvető tipográfiai kiemeléseket támogatja a program

Lehet egy szó *félkövér*, /dőlt/, _aláhúzva_, =szó szerinti=, ~kód~ és +áthúzva+.

** Jelölő négyzetet is használhatunk

- [X] Első feladat
- [ ] Második feladat
- [ ] Harmadik feladat

Kattintás a jelölőnégyzetre átváltja azt. Új elem létrehozása a sor végén az új-sor gomb megnyomásával a is lehetséges.

* Keresés
** Elég sok kereső operátort támogat a program

Rá lehet keresni például állapotra, címkékre, ütemezésre vagy határidőre, stb.

Erről többet a http://www.orgzly.com/help#search oldalon tanulhatsz.

** A keresési kifejezéseket el lehet menteni, hogy gyorsan hozzáférjünk később

Próbáld ki a kész kereséseket a navigációs fiókban és tekintsd meg ott a lekérdezéseket.

Létrehozhatsz saját elmentett kereséseket a navigációs fiókban a "Keresés"-re koppintva.

* Szinkronizálás

** A jegyzettömböket szövegfáljként lehet menteni

A mentett fájlok formátuma “Org mode”.

** A tárolók típusa

Szinkronizálni lehet a jegyzettömböket egy könyvtárral a mobil eszközön, az SD kártyán, vagy a Dropbox-ban.
