Orgzly'e Hoşgeldiniz!

* Notlar
** Click on the note to open it
** Click and hold the note to select it

Birden fazla not seçebilirsiniz.

** Fling note right to open its quick-menu

Fling it left to open a different menu.

** Bir notun alt notlarını yanındaki simgeye tıklayarak gizleyebilirsiniz

Long-click the icon to unfold entire subtree.

*** Sahip olabileceğiniz seviyelerin sınırı yoktur
Notlarınızı daha iyi düzenlemek için bunu kullanın

** Not etiketleri olabilir :etiket1:tag2:
Alt not etiketleri devralır :tag3:

If you search for notes with tag “tag1” using “t.tag1” query, this note will be included in search results.

*** A note that has the =ARCHIVE= tag set is grayed out :ARCHIVE:

** TODO Notlar bir durum belirtebilir

Ayarlardan TODO, NEXT, DONE gibi istediğiniz kadar durum yapılandırabilirsiniz.

*** İki tür durum vardır: to-do ve done

*** DONE bu /done/ durumda bir nottur
CLOSED: [2018-01-24 Çarş. 17:00]

** Notların yapılması için bir zaman belirlenebilir
SCHEDULED: <2015-02-20 Cuma 15:15>

Belirlenen zamanlara tekrarlayıcı ekleyebilirsiniz
SCHEDULED: <2015-02-16 Mon .+2d>

** Notlara son teslim tarihi de ekleyebilirsiniz
DEADLINE: <2015-02-20 Cuma>

** Belirlenen zamanlar ve son teslim tarihleri için hatırlatıcılar desteklenmektedir

Hatırlatıcılar başlangıçta devredışı olacak şekilde tanımlandılar ve ayarlardan etkinleştirilebilinirler.

** [#A] Notların öncelikleri olabilir

Önceliklerin numarasını ayarlardan değiştirebilirsiniz. You can also change default priority - assumed priority for notes without one set.

** Note can include links

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzly.com) or visit a webpage ([[http://www.orgzly.com][Orgzly.com]]).

You can also link to another note or notebook within the app.

See http://www.orgzly.com/help#links for more information.

** Temel yazı karakteri önemi desteklenmektedir

Kelimeleri * kalın *, / italik /, _altıçizili_, = kelimesi kelimesine =, ~ kod ~ ve + doğrudan vurgulama + yapabilirsiniz.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press new-line button at the end of the line to create a new item.

* Arama
** Birçok arama operatörü desteklenmektedir

Notları sınıfına, etiketine, zamanlanmış veya son teslim zamanı vb. Göre arayabilirsiniz.

Daha fazlası için http://www.orgzly.com/help#search siteyi görün.

** Arama sorguları hızlı sorgu için kaydedilebilir

Gezinme penceresinden örnek aramaları deneyin ve kullandıkları soruları not edin.

Gezinme penceresinde bulunan "Aramalar" ı tıklayarak kendi kaydedilmiş aramalarınızı oluşturabilirsiniz.

* Senkronizasyon

** Dizüstü bilgisayarlar düz metin dosyaları olarak kaydedilebilir

Dosyalar "Org mode" tarafından kullanılmış formatları içerir.

** Konum (depo) türü

Dizüstü bilgisayarlarınızı mobil cihazınızdaki, SD kartınızdaki veya Dropbox'taki bir dizinde senkronize şekilde tutabilirsiniz.
