Orgzly'e Hoşgeldiniz!

* Notlar
** Açmak için nota tıklayın
** Notu seçmek için tıklayın ve basılı tutun

Birden fazla not seçebilirsiniz.

** Hızlı menüyü açmak için notu sağa kaydırın

Farklı bir menüye ulaşmak için notu sola kaydırın.

** Bir notun alt notlarını yanındaki simgeye tıklayarak gizleyebilirsiniz

Tüm alt ağacı açmak için simgeye uzun tıklayın.

*** Sahip olabileceğiniz seviyelerin sınırı yoktur
Notlarınızı daha iyi düzenlemek için bunu kullanın

** Notların etiketleri olabilir :tag1:tag2:
Alt not etiketleri devralır :tag3:

If you search for notes with tag “tag1” using “t.tag1” query, this note will be included in search results.

*** A note that has the =ARCHIVE= tag set is grayed out :ARCHIVE:

** TODO Notlar bir durum belirtebilir

Ayarlardan TODO, NEXT, DONE gibi istediğiniz kadar durum yapılandırabilirsiniz.

*** İki tür durum vardır: to-do ve done

*** DONE bu /done/ durumda bir nottur
CLOSED: [2021-07-20 Sal. 11:10]

** Notların yapılması için bir zaman belirlenebilir
SCHEDULED: <2015-02-20 Cuma 15:15>

Belirlenen zamanlara tekrarlayıcı ekleyebilirsiniz
SCHEDULED: <2015-02-16 Pzt. .+1d>

** Notlara son teslim tarihi de ekleyebilirsiniz
DEADLINE: <2015-02-20 Cuma>

** Belirlenen zamanlar ve son teslim tarihleri için hatırlatıcılar desteklenmektedir

Hatırlatıcılar başlangıçta devredışı olacak şekilde tanımlandılar ve ayarlardan etkinleştirilebilinirler.

** [#A] Notların öncelikleri olabilir

Önceliklerin numarasını ayarlardan değiştirebilirsiniz. You can also change default priority - assumed priority for notes without one set.

** Not bağlantılar içerebilir

Bir telefon numarası çevirin (tel:555-0199), SMS gönderin (sms:555-0199), e-posta oluşturun (mailto:support@orgzly.com) veya bir web sayfasını ziyaret edin ([[https://www.orgzly.com][Orgzly.com]]).

Ayrıca uygulama içinde başka bir nota veya not defterine bağlantı verebilirsiniz.

Daha fazla bilgi için https://www.orgzly.com/help#links adresine bakın.

** Temel yazı karakteri önemi desteklenmektedir

Kelimeleri * kalın *, / italik /, _altıçizili_, = kelimesi kelimesine =, ~ kod ~ ve + doğrudan vurgulama + yapabilirsiniz.

** Onay kutusu listesi kullanılabilir

- [X] Görev 1
- [ ] Görev 2
- [ ] Görev 3

Değiştirmek için onay kutusunu tıklayın. Yeni bir öğe oluşturmak için satırın sonundaki yeni satır düğmesine tıklayın.

* Arama
** Birçok arama operatörü desteklenmektedir

Notları sınıfına, etiketine, zamanlanmış veya son teslim zamanı vb. Göre arayabilirsiniz.

Daha fazlası için https://www.orgzly.com/help#search siteyi görün.

** Arama sorguları hızlı sorgu için kaydedilebilir

Gezinme penceresinden örnek aramaları deneyin ve kullandıkları soruları not edin.

Gezinme penceresinde bulunan "Aramalar" ı tıklayarak kendi kaydedilmiş aramalarınızı oluşturabilirsiniz.

* Senkronizasyon

** Dizüstü bilgisayarlar düz metin dosyaları olarak kaydedilebilir

Dosyalar "Org mode" tarafından kullanılmış formatları içerir.

** Konum (depo) türü

Dizüstü bilgisayarlarınızı mobil cihazınızdaki, SD kartınızdaki veya Dropbox'taki bir dizinde senkronize şekilde tutabilirsiniz.
