Orgzly'e Hoşgeldiniz!

Notlar
Açmak için nota tıklayın
Notu seçmek için tıklayın ve basılı tutun

Birden fazla not seçebilirsiniz.

Hızlı menü nota sağ tıklanırsa açılır

Nota sol tıklanırsa farklı bir menü açılır.

Yanındaki simgeler tıklandığında alt notları içeren notlar kapanır
Sahip olabileceğiniz seviyelerin sınırı yoktur
Notlarınızı daha iyi düzenlemek için bunu kullanın

Not etiketleri olabilir :etiket1:tag2:
Alt not etiketleri devralır :tag3:

Eğer "Tag1" etiketi içeren notları ararsanız, bu not da döndürülür.

TODO Not bir durumu belirtebilir

Kullanılacak herhangi bir sınıfta durumu yapılandırabilirsiniz: TODO, NEXT, DONE, vb.

İki tür sınıf vardır: to-do ve done

DONE Bu notta bir sınıf türüdür
CLOSED: [2018-01-24 Çarş. 17:00]

Not belirlenmiş bir zaman içerebilir
SCHEDULED: <2015-02-20 Cuma 15:15>

Zamanlar bir tekrarlayıcı olabilir
SCHEDULED: <2015-02-16 Mon .+2d>

Ayrıca zaman sınırı olarak bir tarih ayarlayabilirsiniz
DEADLINE: <2015-02-20 Cuma>

** Reminders for scheduled and deadline times are supported

They are disabled by default and need to be enabled in Settings.

** [#A] Note can have a priority

You can change the number of priorities in Settings. You can also change default priority - assumed priority for notes without one set.

** Note can include links

Dial a phone number (tel:555-0199), send SMS (sms:555-0199), compose email (mailto:support@orgzly.com) or visit a webpage ([[http://www.orgzly.com][Orgzly.com]]).

You can also link to another note or notebook within the app.

See http://www.orgzly.com/help#links for more information.

Temel yazı karakteri önemi desteklenmektedir

Kelimeleri * kalın *, / italik /, _altıçizili_, = kelimesi kelimesine =, ~ kod ~ ve + doğrudan vurgulama + yapabilirsiniz.

** Checkbox list is available

- [X] Task 1
- [ ] Task 2
- [ ] Task 3

Click the checkbox to toggle it. Press new-line button at the end of the line to create a new item.

Arama
Birçok arama operatörü desteklenmektedir

Notları sınıfına, etiketine, zamanlanmış veya son teslim zamanı vb. Göre arayabilirsiniz.

Daha fazlası için http://www.orgzly.com/help#search siteyi görün.

Arama sorguları hızlı sorgu için kaydedilebilir

Gezinme penceresinden örnek aramaları deneyin ve kullandıkları soruları not edin.

Gezinme penceresinde bulunan "Aramalar" ı tıklayarak kendi kaydedilmiş aramalarınızı oluşturabilirsiniz.

Senkronizasyon

Dizüstü bilgisayarlar düz metin dosyaları olarak kaydedilebilir

Dosyalar "Org mode" tarafından kullanılmış formatları içerir.

Konum (depo) türü

Dizüstü bilgisayarlarınızı mobil cihazınızdaki, SD kartınızdaki veya Dropbox'taki bir dizinde senkronize şekilde tutabilirsiniz.
