Benvenuto su Orgzly!

* Note
** Clicca sulla nota per aprirla
** Tieni premuta la nota per selezionarla

Puoi selezionare più note.

** Tieni premuto e muovi velocemente a destra per aprire il suo menu rapido

Trascina verso sinistra per aprire un menu diverso.

** Apri una nota che contiene sotto-note premendo sull'icona vicina ad essa

Fare clic sull'icona per dispiegare l'intero sotto-albero.

** Non ci sono limiti al numero di livelli che puoi avere
**** Usalo per meglio organizzare le tue note

*** Ora puoi avere anche le etichette :tag1:tag2:
*** La sotto-nota eredita l'etichetta :tag3:

Se si cerca note con tag “tag1” utilizzando la query “t.tag1”, questa nota sarà inclusa nei risultati di ricerca.

*** A note that has the =ARCHIVE= tag set is grayed out :ARCHIVE:

** TODO La nota può avere uno stato

È possibile configurare qualsiasi numero di stati da usare: TODO, NEXT, DONE, ecc.

*** Ci sono due /tipi/ di stati: todo e done

*** DONE Questa è una nota con il tipo di stato /Done/
CLOSED: [2018-01-24 Mer 17:00]

** La nota può avere un orario programmato
SCHEDULED: <2015-02-20 Ven 15:15>

*** Gli orari possono avere una ripetizione
SCHEDULED: <2015-02-16 Lun .+2d>

** Puoi anche stabilire una scadenza
DEADLINE: <2015-02-20 Ven>

** Sono supportati i promemoria per i task pianificati e per le scadenze

Sono disabilitati di default e devono essere abilitati nelle impostazioni.

** [#A] Le note possono avere una priorità

È possibile modificare il numero di priorità nelle impostazioni. Puoi anche cambiare la priorità predefinita - la proprietà impostata per le note in cui non viene specificata.

** Le note possono includere link

Digita un numero di telefono (tel:555-0199), invia SMS (sms:555-0199), componi un'email (mailto:support@orgzly.com) o visita una pagina web ([[http://www.orgzly.com][Orgzly.com]]).

Puoi anche collegarti a un'altra nota o a un taccuino all'interno dell'app.

Vai su http://www.orgzly.com/help#links per maggiori informazioni.

** Sono supportati i livelli di formattazione base

Puoi usare parole in *grassetto*, /corsivo/, _sottolineato_, =scandito=, ~tipo codice~ e +barrato+.

** È disponibile una lista di checkbox

- [X] Attività 1
- [ ] Attività 2
- [ ] Attività 3

Fare clic sulla casella per cambiare lo stato. Premere il pulsante nuova riga alla fine della linea per creare un nuovo elemento.

* Cerca
** Sono supportati molti operatori di ricerca

Puoi cercare nelle note a seconda dello stato, del tag, della programmazione o della scadenza ecc.

Vai su http://www.orgzly.com/help#search per saperne di più.

** Le stringhe di ricerca possono essere salvate per un rapido accesso

Prova a fare ricerche semplici dal cassetto di navigazione e nota quali stringhe usino.

Puoi creare le proprie ricerche salvate premendo su "Ricerche" nel menu di navigazione.

* Sincronizzazione

** I taccuini possono essere salvati come file di testo

I file sono nel formato usato da "Org mode".

** Tipo di percorso (repository)

Puoi tenere sincronizzati i taccuini sul tuo dispositivo mobile in una directory, su di una scheda di memoria o su Dropbox.
